import { getServerSession } from 'next-auth'
import './globals.css'
import { SessionProvider } from '@/components/SessionProvider'
import { authOptions } from './api/auth/[...nextauth]/route'
import Login from '@/components/Login'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (
            <div>
              {children}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
